# Generated by Django 2.1.8 on 2019-12-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('street_address', models.CharField(max_length=32)),
                ('suburb', models.CharField(max_length=32)),
                ('postcode', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('contact_name', models.CharField(max_length=32)),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('phone_number', models.CharField(max_length=32)),
            ],
        ),
    ]
